### ISSUE TITLE
Errors when using Application Default Credentials

### ISSUE THREAD

**Issue by subbu14581** [google/google-auth-library-java#140]
```
Exception in thread "main" java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.api.client.googleapis.auth.oauth2.DefaultCredentialProvider.getDefaultCredential(DefaultCredentialProvider.java:98)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:213)
	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.getApplicationDefault(GoogleCredential.java:191)
	at com.google.cloud.vision.samples.label.LabelApp.getVisionService(LabelApp.java:100)
	at com.google.cloud.vision.samples.label.LabelApp.main(LabelApp.java:73)
```

BUILD FAILURE

**Comment by DIWithers** [comment]
I used C# / Visual Studio for mine but had the same error. Did you download the credentials as per the docs and set your local environment variable (GOOGLE_APPLICATION_CREDENTIALS) with the path to the file?

**Comment by chingor13** [comment]
Yes, to configure ApplicationDefaultCredentials locally or in a non-GCP environment you will want to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the *path* to your credentials file (downloadable from the Google Cloud Console).

More information is available at the link in the error message: https://cloud.google.com/docs/authentication/production

**Comment by ansh-mehta** [comment]
I have tried all these, still getting the same error. PLEASE HELP!

**Comment by ansh-mehta** [comment]
> @ansh-mehta I just came across this issue while searching for a way to get Java with SecurityManager to be disabled or to work with the Google Application Default Credentials (for ElasticSearch, related to this: https://www.elastic.co/guide/en/elasticsearch/plugins/7.10/repository-gcs-usage.html#repository-gcs-service-authentication). Perhaps you were running into the same issue (Java SecurityManager interfering with Google Application Default Credentials)?

I don't remember at all 😅, long time!
